/*
* generated by Xtext
*/
package org.pror.presentation.wrspm.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WrspmDomainmodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/pror/presentation/wrspm/xtext/parser/antlr/internal/InternalWrspmDomainmodel.tokens");
	}
}
