/*
* generated by Xtext
*/
package org.pror.presentation.wrspm.xtext.ui.contentassist;

import org.pror.presentation.wrspm.xtext.ui.contentassist.AbstractWrspmDomainmodelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WrspmDomainmodelProposalProvider extends AbstractWrspmDomainmodelProposalProvider {

}
