
/*
 * generated by Xtext
 */
 
package org.pror.presentation.wrspm.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class WrspmDomainmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.pror.presentation.wrspm.xtext.ui.internal.WrspmDomainmodelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.pror.presentation.wrspm.xtext.ui.internal.WrspmDomainmodelActivator.getInstance().getInjector("org.pror.presentation.wrspm.xtext.WrspmDomainmodel");
	}
	
}
