/*
 * generated by Xtext
 */
package org.pror.presentation.wrspm.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WrspmDomainmodelRuntimeModule extends org.pror.presentation.wrspm.xtext.AbstractWrspmDomainmodelRuntimeModule {

}
