/*
* generated by Xtext
*/
package org.pror.presentation.wrspm.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class WrspmDomainmodelTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
