/*
 * generated by Xtext
 */
package org.pror.presentation.wrspm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WrspmDomainmodelUiModule extends org.pror.presentation.wrspm.xtext.ui.AbstractWrspmDomainmodelUiModule {
	public WrspmDomainmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
