/*
* generated by Xtext
*/
package org.pror.presentation.wrspm.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.pror.presentation.wrspm.xtext.services.WrspmDomainmodelGrammarAccess;

public class WrspmDomainmodelParser extends AbstractContentAssistParser {
	
	@Inject
	private WrspmDomainmodelGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.pror.presentation.wrspm.xtext.ui.contentassist.antlr.internal.InternalWrspmDomainmodelParser createParser() {
		org.pror.presentation.wrspm.xtext.ui.contentassist.antlr.internal.InternalWrspmDomainmodelParser result = new org.pror.presentation.wrspm.xtext.ui.contentassist.antlr.internal.InternalWrspmDomainmodelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPartAccess().getAlternatives(), "rule__Part__Alternatives");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getDefinitionAccess().getGroup(), "rule__Definition__Group__0");
					put(grammarAccess.getDomainModelAccess().getElementsAssignment(), "rule__DomainModel__ElementsAssignment");
					put(grammarAccess.getAnyTextAccess().getContentAssignment(), "rule__AnyText__ContentAssignment");
					put(grammarAccess.getEntityAccess().getRefAssignment_1(), "rule__Entity__RefAssignment_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_1(), "rule__Definition__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.pror.presentation.wrspm.xtext.ui.contentassist.antlr.internal.InternalWrspmDomainmodelParser typedParser = (org.pror.presentation.wrspm.xtext.ui.contentassist.antlr.internal.InternalWrspmDomainmodelParser) parser;
			typedParser.entryRuleDomainModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public WrspmDomainmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WrspmDomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
